### ISSUE TITLE
UI get very slow on large flow

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#586]

**Comment by JiaFei1991** [comment]
Rubix-flow editor becomes laggy when a large number of nodes are loaded into the editor. This is mainly caused by loading every node, including the nodes stored in folders, into the editor all at once. 

The current solution is to dynamically load the nodes that belong to the same level into the editor, thus reducing the total number of nodes. This solution is somewhat effective when the number of nodes in the same level is small. The editor still exhibits lag when the level being displayed contains multiple folders that each have multiple sub-flow inputs and outputs. However, to fully implement this feature, the editing and saving functions also need to be changed to use dynamic node loading. This could lead to a bug-prone component.

I think the root reason for this problem is how React-flow handles a large number of nodes because our front-end is only manipulating the JSON objects that represent nodes and using React-flow's API to show them in the editor.
